const http=require('http'),fs=require('fs'),path=require('path');const {URL}=require('url');const {loadCatalog}=require('./server/catalog');const {CATEGORIES,spin}=require('./server/roulette');const {status}=require('./server/status');
const PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public');const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};
function sendJson(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body)});res.end(body)}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>100000){no(new Error('too large'));req.destroy()}});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on('error',no)})}
function serve(res,file){fs.stat(file,(e,st)=>{if(e||!st.isFile()){const d=fs.readFileSync(path.join(PUBLIC,'index.html'));res.writeHead(200,{'content-type':MIME['.html']});return res.end(d)}res.writeHead(200,{'content-type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream'});fs.createReadStream(file).pipe(res)})}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);
 if(req.method==='GET'&&u.pathname==='/api/v1/health')return sendJson(res,200,{ok:true});
 if(req.method==='GET'&&u.pathname==='/api/v1/catalog/status')return sendJson(res,200,status());
 if(req.method==='GET'&&u.pathname==='/api/v1/config'){const c=loadCatalog();return sendJson(res,200,{categories:CATEGORIES,ui:c.ui,cities:c.cities,cityMeta:c.cityMeta,stats:{ideas:c.ideas.length,locations:c.locations.length,markets:c.markets.length,cities:c.cities.length}})}
 if(req.method==='GET'&&u.pathname==='/api/v1/cities'){const c=loadCatalog(),q=(u.searchParams.get('q')||'').toLowerCase();const list=c.cities.filter(x=>!q||`${x.name} ${x.region}`.toLowerCase().includes(q)).slice(0,50);return sendJson(res,200,{cities:list})}
 if(req.method==='POST'&&u.pathname==='/api/v1/spin'){try{const c=loadCatalog();return sendJson(res,200,spin(c,await body(req)))}catch(e){console.error(e);return sendJson(res,500,{error:'Не удалось подобрать вариант'})}}
 if(req.method!=='GET')return sendJson(res,405,{error:'Method not allowed'});const requested=decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname),file=path.normalize(path.join(PUBLIC,requested));if(!file.startsWith(PUBLIC))return sendJson(res,403,{error:'Forbidden'});serve(res,file);
}).listen(PORT,()=>console.log(`davai. v7 → http://localhost:${PORT}`));
