const {buildLocationLinks}=require('./links');
const CATEGORIES=['Романтика','Еда','Активное','Творчество','Игры','Культура','Природа','Мини-путешествие','Необычное'];
const pick=a=>a[Math.floor(Math.random()*a.length)];
const budgetRank={бесплатно:0,низкий:1,средний:2,высокий:3,любой:2};const budgetCaps={free:0,'1000':1,'3000':1,'5000':2,'10000':2,'20000':3,premium:99,any:99};
function budgetMatches(v,w){if(!w||w==='any')return true;const r=budgetRank[v]??2;if(w==='premium')return r>=3;return r<=budgetCaps[w];}
function durationBucket(d){const s=String(d||'');if(s.includes('30'))return .5;if(s==='до 1 часа')return .75;if(s.includes('1–2'))return 1.5;if(s.includes('1–3'))return 2;if(s.includes('2–3'))return 2.5;if(s.includes('2–4'))return 3;if(s.includes('3+'))return 6;return 2;}
function timeMatches(d,w){if(!w||w==='any')return true;const h=durationBucket(d);return ({'30m':h<=.5,'1h':h<=1,'2h':h<=2,'4h':h<=4,evening:h<=4,halfday:h<=6,day:h>=3,weekend:h>=3})[w]??true;}
function moodMatches(m,w){if(!w||w==='any')return true;const s=(m||'').toLowerCase(),map={romantic:['романт'],calm:['спокой','уют'],active:['актив','энерг'],fun:['весел','игров'],unusual:['необыч','приключ'],creative:['творч']};return(map[w]||[]).some(x=>s.includes(x));}
function filterLocations(catalog,filters,category){let arr=catalog.locations;const scope=filters.scope||'moscow-mo';if(scope==='city'){arr=arr.filter(l=>l.city_id===filters.city_id||(!l.city_id&&String(l.city||'').toLowerCase()===String(filters.city_name||'').toLowerCase())||(category==='Мини-путешествие'&&filters.city_region&&l.region_scope===filters.city_region));}else{const allowed=catalog.ui.scopes.find(x=>x.id===scope)?.markets||['moscow','moscow-oblast'];arr=arr.filter(l=>allowed.includes(l.market_id));}return arr.filter(l=>!category||(l.best_for||[]).includes(category));}
function spin(catalog,filters){const budget=filters.budget||'any',time=filters.time||'any',mood=filters.mood||'any',manual=filters.category&&filters.category!=='random'?filters.category:null;
 const eligible=CATEGORIES.filter(cat=>cat==='Мини-путешествие'?filterLocations(catalog,filters,cat).some(l=>budgetMatches(l.budget,budget)):catalog.ideas.some(i=>i.category===cat&&budgetMatches(i.budget,budget)&&timeMatches(i.duration,time)&&moodMatches(i.mood,mood)));
 const category=manual&&eligible.includes(manual)?manual:pick(eligible.length?eligible:CATEGORIES.filter(x=>x!=='Мини-путешествие'));
 if(category==='Мини-путешествие'){let ls=filterLocations(catalog,filters,category).filter(l=>budgetMatches(l.budget,budget));if(!ls.length)ls=filterLocations(catalog,filters,category);const result=pick(ls);if(!result)return spin(catalog,{...filters,category:'random'});return{category,kind:'location',result:{...result,links:buildLocationLinks(result)},suggestions:[]};}
 let ideas=catalog.ideas.filter(i=>i.category===category&&budgetMatches(i.budget,budget)&&timeMatches(i.duration,time)&&moodMatches(i.mood,mood));if(!ideas.length)ideas=catalog.ideas.filter(i=>i.category===category);const result=pick(ideas);const suggestions=filterLocations(catalog,filters,category).sort(()=>Math.random()-.5).slice(0,3).map(x=>({...x,links:buildLocationLinks(x)}));return{category,kind:'idea',result,suggestions};}
module.exports={CATEGORIES,spin};
