#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const {spawnSync}=require('child_process');
const ROOT=path.join(__dirname,'..'), CITIES=path.join(ROOT,'data','russia-cities.json'), OUTDIR=path.join(ROOT,'data','city-locations'), REGIONDIR=path.join(ROOT,'data','region-locations'), INBOX=path.join(ROOT,'data','inbox'), STATE=path.join(ROOT,'data','sync-state.json');
function read(p,d){try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return d}}function write(p,d){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(d,null,2))}function slug(v){return String(v||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9]+/gi,'-').replace(/^-+|-+$/g,'')}
function run(args){const r=spawnSync(process.execPath,[path.join('scripts','import-osm.js'),...args],{cwd:ROOT,stdio:'inherit',env:process.env});return r.status===0}
function merge(file,cands){const data=read(file,{locations:[]}),incoming=(cands||[]).filter(x=>x.quality?.decision==='auto_publish'),seen=new Set(incoming.map(x=>x.source_id)),byId=new Map();for(const old of data.locations||[]){let x={...old};if(x.source==='osm'&&!seen.has(x.source_id)){x.missed_syncs=(x.missed_syncs||0)+1;if(x.missed_syncs>=3)x.status='inactive-auto';}byId.set(x.source_id,x);}for(const x of incoming)byId.set(x.source_id,{...byId.get(x.source_id),...x,status:'auto-published',missed_syncs:0,last_seen_at:new Date().toISOString()});data.locations=[...byId.values()];data.updated_at=new Date().toISOString();write(file,data);return data.locations.length}
if(!fs.existsSync(CITIES)){console.log('Каталога городов нет — создаю…');const r=spawnSync(process.execPath,[path.join('scripts','sync-cities.js')],{cwd:ROOT,stdio:'inherit',env:process.env});if(r.status!==0)process.exit(r.status||1)}
const reg=read(CITIES,{cities:[]});const st=read(STATE,{city_cursor:0,region_cursor:0});const refresh=process.argv.includes('--refresh');const full=process.argv.includes('--full');const cityBatch=full?reg.cities.length:Number(process.env.CITY_SYNC_BATCH||24);const regions=[...new Set(reg.cities.map(x=>x.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));const regionBatch=full?regions.length:Number(process.env.REGION_SYNC_BATCH||6);
let addedFiles=0;
for(let i=0;i<Math.min(cityBatch,reg.cities.length);i++){const c=reg.cities[(st.city_cursor+i)%reg.cities.length];console.log(`\n[город] ${c.name}, ${c.region}`);const args=[`--market=${c.id}`,`--area=${c.name}`,`--region=${c.region}`,`--mode=city`,`--enrich=30`];if(refresh)args.push('--refresh');if(!run(args))continue;const inbox=path.join(INBOX,`${c.id}.city.osm.json`);if(!fs.existsSync(inbox))continue;const q=read(inbox,{locations:[]});merge(path.join(OUTDIR,`${c.id}.json`),q.locations);addedFiles++;}
for(let i=0;i<Math.min(regionBatch,regions.length);i++){const region=regions[(st.region_cursor+i)%regions.length];console.log(`\n[регион / новые stay & spa] ${region}`);const id=`region-${slug(region)}`;const args=[`--market=${id}`,`--area=${region}`,`--mode=region`,`--enrich=80`];if(refresh)args.push('--refresh');if(!run(args))continue;const inbox=path.join(INBOX,`${id}.region.osm.json`);if(!fs.existsSync(inbox))continue;const q=read(inbox,{locations:[]});const chosen=(q.locations||[]).filter(x=>x.quality?.decision==='auto_publish').map(x=>({...x,region_scope:region}));merge(path.join(REGIONDIR,`${slug(region)}.json`),chosen);}
st.city_cursor=(st.city_cursor+cityBatch)%Math.max(1,reg.cities.length);st.region_cursor=(st.region_cursor+regionBatch)%Math.max(1,regions.length);st.updated_at=new Date().toISOString();write(STATE,st);console.log(`\nГотово. Обработано городов: ${Math.min(cityBatch,reg.cities.length)}, регионов: ${Math.min(regionBatch,regions.length)}. Файлов городов обновлено: ${addedFiles}.`);
